# **Homework Assignment #6**
Brandon Luy
11532759


1.

![](https://drive.google.com/uc?export=view&id=1q3eqYARfI4WgpsRk0hkMkfIcYicwawFf)

2.

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_predict
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score


phoneme = fetch_openml(name="phoneme")
X = phoneme.data
y = phoneme.target
randomly = np.random.RandomState(42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state = randomly)


#classifiers
per = Perceptron(tol=1e-3, random_state=0)

gaus = GaussianNB().fit(X_train, y_train)

knn = KNeighborsClassifier(n_neighbors=5).fit(X_train, y_train)

sv = SVC(probability=True, gamma='auto',
                random_state=randomly).fit(X_train, y_train)

dt =  DecisionTreeClassifier(random_state=randomly,
                                    max_depth=10).fit(X_train, y_train)

dt.fit(X_train, y_train)
per.fit(X_train, y_train)
gaus.fit(X_train, y_train)
sv.fit(X_train,y_train)
knn.fit(X_train, y_train)
predictions = dt.predict(X_test)
predictions2 = per.predict(X_test)
predictions3 = gaus.predict(X_test)
predictions4 = sv.predict(X_test)
predictions5 = knn.predict(X_test)

print("Decision Tree Accuracy: ",(accuracy_score(y_test, predictions)))
print("Preceptron Accuracy: ",(accuracy_score(y_test, predictions2)))
print("Gaussian Accuracy: ",(accuracy_score(y_test, predictions3)))
print("SVC Accuracy: ",(accuracy_score(y_test, predictions4)))
print("KNN Accuracy: ",(accuracy_score(y_test, predictions5)))

y1 = accuracy_score(y_test, predictions)
y2 = accuracy_score(y_test, predictions2)
y3 = accuracy_score(y_test, predictions3)
y4 = accuracy_score(y_test, predictions4)
y5 = accuracy_score(y_test, predictions5)


classifiers = [
               predictions, 
               predictions2,
               predictions3,
               predictions4,
               predictions5
]


Decision Tree Accuracy:  0.8553811659192825
Preceptron Accuracy:  0.7460762331838565
Gaussian Accuracy:  0.7572869955156951
SVC Accuracy:  0.851457399103139
KNN Accuracy:  0.8677130044843049


3.

points to remember:


*   restart env on each iteration
*   Get max steps each step
*   update Q table after each time getting max step
*   keep counter (i.e. iterate total number of rewards at end) 

Referenced: https://towardsdatascience.com/value-iteration-for-v-function-d7bcccc1ec24 for help with understanding algorithm better





In [ ]:
'''
A frozenlake-v0 is a 4x4 grid world which looks as follows:
SFFF       (S: starting point, safe)
FHFH       (F: frozen surface, safe)
FFFH       (H: hole, fall to your doom)
HFFG       (G: goal, where the frisbee is located)
Additionally, there is a little uncertainity in the agent movement.
Q Learning - A simple q Learning algorithm is employed for the task.
The q values are stored in a table and these are updated in each iteration
to converge to their optimum values.
'''

import gym
import numpy as np
import random
import math

def main():
  env = gym.make("FrozenLake-v0")

  num_episodes = 10000
  max_steps = 50
  gamma = 0.99
  learning_rate = 0.1
  discount_rate = 0.99
  epsilon = 1.0
  max_epsilon = 1.0
  min_epsilon = 0.01
  decay_rate = 0.01

  # initialize the Q table
  state_space_size = env.observation_space.n
  action_space_size = env.action_space.n
  Q = np.zeros((state_space_size, action_space_size))
  rewards = []

  for i in range(num_episodes):
    state = env.reset()
    curr = 0
    complete = False
    for j in range(max_steps):
      rate_threshold = random.uniform(0,1)
      if rate_threshold > epsilon:
        action = np.argmax(Q[state:])
      else:
        action = env.action_space.sample()
      #log results of step all parameters that go into 

      new_state, reward, complete, info = env.step(action)
      #increment total reward
      curr += reward
      new = ((gamma*np.max(Q[new_state, :])) - Q[state, action]) + reward
      Q[state, action] += learning_rate * new
      state = new_state
      #if the number of steps has been completed
      if complete == True:
        break
      if i == (num_episodes -1):
        env.render()
            #Update Epsilon
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*i) 
    rewards.append(curr)
  print(np.around(Q,6))
  print('score:', np.mean(rewards))

main()

  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
score: 0.0
